### PR TITLE
Add Task GLibC 2.5

### PR DESCRIPTION
**Pull request by juancarlospaco**
- Add Task to build Nim to C, linked to GLibC 2.5 (year ~2000, x86_64, Dynamic, Not static).

:slightly_smiling_face:

### CODE REVIEW

**Comment by juancarlospaco** [comment]
I always forgot the manual Squash.
But on Github on the Merge button, theres a tiny arrow, if you click it theres an option `Squash & Merge`.

You should put the Travis badge on the Readme (I dont know how to do it on Org).

**Comment by juancarlospaco** [comment]
@kaushalmodi Let me know any comments, is re-sync'd with master :grey_exclamation: :slightly_smiling_face: :+1:

**Comment by kaushalmodi** [comment]
@juancarlospaco Hello I have your commit rebased to origin/master locally. In future, please do rebase and not merge. I like to see linear commit history for new commits.

I'll merge it soon.

**Comment by kaushalmodi** [comment]
I have merged this in:
- https://github.com/kaushalmodi/nim_config/commit/2257c7713b9f3f50ed8fced615b1bc81df6abde3
- https://github.com/kaushalmodi/nim_config/commit/3ae2c45e2d81931bc5613cd93d545ab25a7b579b

**Pull request closed without merging**
